"use client";

import { useEffect, useState } from "react";
import DashboardLayout from "@/components/DashboardLayout";
import { Search, Calendar, History, ShieldAlert, Sparkles } from "lucide-react";
import { API_BASE_URL } from "@/utils/api";

export default function HistoryPage() {
  const [history, setHistory] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState("");
  const [filterHorizon, setFilterHorizon] = useState("all");

  const fetchHistory = async () => {
    try {
      const token = localStorage.getItem("astracast_token");
      const res = await fetch(`${API_BASE_URL}/predict/history`, {
        headers: { "Authorization": `Bearer ${token}` }
      });
      if (res.ok) {
        const json = await res.json();
        setHistory(json);
      }
    } catch (e) {
      console.error(e);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchHistory();
  }, []);

  const filteredHistory = history.filter(item => {
    const matchesSearch = item.expected_radiation_category?.toLowerCase().includes(search.toLowerCase()) || 
                          item.prediction_horizon?.toLowerCase().includes(search.toLowerCase()) ||
                          item.explanation?.toLowerCase().includes(search.toLowerCase());
                          
    const matchesHorizon = filterHorizon === "all" || item.prediction_horizon === filterHorizon;
    
    return matchesSearch && matchesHorizon;
  });

  return (
    <DashboardLayout>
      <div className="flex flex-col gap-6 font-sans">
        <div>
          <h1 className="text-2xl font-bold tracking-tight text-white flex items-center gap-2">
            Forecasting History
          </h1>
          <p className="text-slate-400 text-xs mt-1">Audit log of all AI predictions generated by the system.</p>
        </div>

        {/* Filter Toolbar */}
        <div className="flex flex-col sm:flex-row gap-3 bg-slate-900/20 border border-slate-800/80 rounded-2xl p-4 backdrop-blur-sm justify-between">
          <div className="relative flex-1">
            <Search className="absolute left-3 top-3 h-4 w-4 text-slate-500" />
            <input
              type="text"
              placeholder="Search history by category, horizon, or explanation..."
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              className="w-full pl-10 pr-4 py-2.5 bg-slate-950/60 border border-slate-850 rounded-xl focus:border-blue-500 text-xs outline-none text-slate-200 placeholder-slate-650"
            />
          </div>
          
          <select
            value={filterHorizon}
            onChange={(e) => setFilterHorizon(e.target.value)}
            className="px-4 py-2.5 bg-slate-950/60 border border-slate-850 rounded-xl text-xs text-slate-400 outline-none focus:border-blue-500"
          >
            <option value="all">All Horizons</option>
            <option value="30m">30 Minutes</option>
            <option value="6h">6 Hours</option>
            <option value="12h">12 Hours</option>
            <option value="24h">24 Hours</option>
            <option value="3d">3 Days</option>
            <option value="7d">7 Days</option>
          </select>
        </div>

        {/* Results Data Table */}
        <div className="bg-slate-900/10 border border-slate-800/80 rounded-2xl overflow-hidden backdrop-blur-sm">
          {loading ? (
            <div className="p-12 text-center text-slate-500 text-xs">Loading logs...</div>
          ) : filteredHistory.length === 0 ? (
            <div className="p-12 text-center text-slate-500 text-xs">No historical projections found.</div>
          ) : (
            <div className="overflow-x-auto">
              <table className="w-full text-left text-xs border-collapse">
                <thead>
                  <tr className="bg-slate-900/60 border-b border-slate-800/60 text-slate-400 uppercase tracking-widest text-[9px] font-bold">
                    <th className="px-5 py-3.5">Timestamp</th>
                    <th className="px-5 py-3.5">Horizon</th>
                    <th className="px-5 py-3.5 text-right">Storm Prob</th>
                    <th className="px-5 py-3.5 text-right">Expected Wind</th>
                    <th className="px-5 py-3.5 text-right">Expected Electron</th>
                    <th className="px-5 py-3.5 text-right">Expected Bz</th>
                    <th className="px-5 py-3.5 text-center">Radiation</th>
                    <th className="px-5 py-3.5 text-right">Confidence</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-800/40 text-slate-300">
                  {filteredHistory.map((item) => (
                    <tr key={item.id} className="hover:bg-slate-900/20 transition-colors">
                      <td className="px-5 py-4 whitespace-nowrap font-mono text-[10px] text-slate-500">
                        {new Date(item.timestamp).toLocaleString()}
                      </td>
                      <td className="px-5 py-4 font-mono font-bold text-blue-400">
                        {item.prediction_horizon}
                      </td>
                      <td className="px-5 py-4 text-right font-semibold">
                        {(item.storm_probability * 100).toFixed(0)}%
                      </td>
                      <td className="px-5 py-4 text-right font-mono text-[11px]">
                        {item.expected_solar_wind_speed?.toFixed(0)} <span className="text-[10px] text-slate-500">km/s</span>
                      </td>
                      <td className="px-5 py-4 text-right font-mono text-[11px]">
                        {item.expected_electron_flux?.toFixed(0)} <span className="text-[10px] text-slate-500">PFU</span>
                      </td>
                      <td className="px-5 py-4 text-right font-mono text-[11px]">
                        {item.expected_imf_bz?.toFixed(2)} <span className="text-[10px] text-slate-500">nT</span>
                      </td>
                      <td className="px-5 py-4 text-center">
                        <span className={`px-2 py-0.5 rounded text-[10px] font-bold ${
                          item.expected_radiation_category === "S0" ? "bg-emerald-500/10 text-emerald-400" : "bg-red-500/10 text-red-400"
                        }`}>
                          {item.expected_radiation_category}
                        </span>
                      </td>
                      <td className="px-5 py-4 text-right font-bold text-slate-200">
                        {item.confidence?.toFixed(0)}%
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </div>
      </div>
    </DashboardLayout>
  );
}
